name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  device_preview: ^1.2.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/MI band.png
    - assets/images/baju.png
    - assets/images/headphone.png
    - assets/images/sepatu.png
    - assets/lottie/lottie_login.json
